spring:
  datasource:
    username: root
    password: jason
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud_shop_demo?characterEncoding=utf-8&useSSL=false

  rabbitmq:
    host: 139.199.228.154
    port: 5672
    username: jsbintask
    password: jsbintask

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
   
management:
  endpoints:
    web:
      exposure:
        include: '*'

env: a
env2: b
